[mypy]
python_version = 3.12
check_untyped_defs = True
disallow_untyped_defs = True
no_implicit_optional = True
explicit_package_bases = True
show_error_codes = True
warn_redundant_casts = True
warn_unused_ignores = True
exclude = (?x)(^|/)tests/fixtures/|03-projects/streamflow-containerized-stream-processing/(airflow|spark)/|03-projects/streamflow-enterprise-analytics-pipeline/airflow/

[mypy-openai]
ignore_missing_imports = True
