USE ROLE ACCOUNTADMIN;

CREATE ROLE IF NOT EXISTS STREAMFLOW_ROLE;

CREATE WAREHOUSE IF NOT EXISTS STREAMFLOW_WH
  WAREHOUSE_SIZE = XSMALL
  AUTO_SUSPEND = 60
  AUTO_RESUME = TRUE
  INITIALLY_SUSPENDED = TRUE;

CREATE DATABASE IF NOT EXISTS STREAMFLOW_DB;

GRANT USAGE ON WAREHOUSE STREAMFLOW_WH TO ROLE STREAMFLOW_ROLE;
GRANT USAGE ON DATABASE STREAMFLOW_DB TO ROLE STREAMFLOW_ROLE;
GRANT CREATE SCHEMA ON DATABASE STREAMFLOW_DB TO ROLE STREAMFLOW_ROLE;

CREATE USER IF NOT EXISTS STREAMFLOW_AGENT
  PASSWORD = '<replace-locally-before-running>'
  DEFAULT_ROLE = STREAMFLOW_ROLE
  DEFAULT_WAREHOUSE = STREAMFLOW_WH
  DEFAULT_NAMESPACE = STREAMFLOW_DB.BRONZE
  MUST_CHANGE_PASSWORD = FALSE;

GRANT ROLE STREAMFLOW_ROLE TO USER STREAMFLOW_AGENT;
