CREATE SCHEMA IF NOT EXISTS STREAMFLOW_DB.BRONZE;

CREATE FILE FORMAT IF NOT EXISTS STREAMFLOW_DB.BRONZE.STREAMFLOW_JSON_FORMAT
  TYPE = JSON
  STRIP_OUTER_ARRAY = FALSE;

CREATE FILE FORMAT IF NOT EXISTS STREAMFLOW_DB.BRONZE.STREAMFLOW_PARQUET_FORMAT
  TYPE = PARQUET
  USE_LOGICAL_TYPE = TRUE;

CREATE STAGE IF NOT EXISTS STREAMFLOW_DB.BRONZE.STREAMFLOW_STAGE
  FILE_FORMAT = STREAMFLOW_DB.BRONZE.STREAMFLOW_JSON_FORMAT;

CREATE TABLE IF NOT EXISTS STREAMFLOW_DB.BRONZE.BRONZE_EVENTS_RAW (
  raw_payload VARIANT NOT NULL,
  source_file STRING,
  source_row_number NUMBER,
  stream_topic STRING NOT NULL DEFAULT 'streamflow.events',
  ingest_run_id STRING NOT NULL,
  loaded_at TIMESTAMP_NTZ NOT NULL DEFAULT CURRENT_TIMESTAMP()
);
